### ISSUE TITLE
Deprecation warnings in workflow

### ISSUE THREAD

**Issue by MikeMcC399** [bahmutov/test-personal-site#1]
## Problem description

The scheduled workflow [.github/workflows/ci.yml](https://github.com/bahmutov/test-personal-site/blob/main/.github/workflows/ci.yml) is disabled due to inactivity.

If it is run manually, it is successful and shows deprecation warnings.

## Steps to reproduce the issue

Fork repository https://github.com/bahmutov/test-personal-site
Enable and run workflow `ci`

View action log ci > cypress-run and note deprecation warnings:

"Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, cypress-io/github-action@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/."

"The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"

## Expected behavior

When run as an example in a fork the workflow should not show deprecation warnings.

## Suggested Fix

Update action versions to resolve deprecations:

| Current version             | Suggested version           |
| --------------------------- | --------------------------- |
| actions/checkout@v2         | actions/checkout@v3         |
| cypress-io/github-action@v2 | cypress-io/github-action@v5 |

In addition as a maintenance task update the following also:

| Current version    | Suggested version  |
| ------------------ | ------------------ |
| ubuntu-20.04       | ubuntu-22.04       |
| "cypress": "6.4.0" | "cypress": "9.7.0" |

To avoid error
"ERROR:cert_verify_proc_builtin.cc" (see
https://github.com/cypress-io/cypress/discussions/22128) run headless in chrome browser.

## Additional information

https://github.com/bahmutov/test-personal-site is referred to in the [More examples](https://github.com/cypress-io/github-action#more-examples) section of the [cypress-io/github-action](https://github.com/cypress-io/github-action) repository.

**Comment by MikeMcC399** [comment]
@bahmutov 

This will fail after  31st May 2023 if not updated.

**Comment by bahmutov** [comment]
I am ok with that, don't want to update this repo and its corresponding blog post.

**Comment by MikeMcC399** [comment]
@bahmutov 

Thank you for your decision!
